trigger builder build

diff --git a/docker/builder/root/usr/bin/build b/docker/builder/root/usr/bin/build
--- a/docker/builder/root/usr/bin/build
+++ b/docker/builder/root/usr/bin/build
@@ -22,12 +22,13 @@ esac
 
 case "$CMD" in
 "cmake")
-    if [ ! -d "$SOURCE_DIR/sysdig" ]; then
-        echo "Missing sysdig source." >&2
+    if [ ! -f "$SOURCE_DIR/sysdig/README.md" ]; then
+        echo "Could not find sysdig source in $SOURCE_DIR/sysdig. ($SOURCE_DIR/sysdig/README.md not found!)" >&2
         exit 1
     fi
 
-    if [ -d "$SOURCE_DIR/libs" ]; then
+    if [ -f "$SOURCE_DIR/libs/README.md" ]; then
+        echo "Found falcosecurity libs source in $SOURCE_DIR/libs"
         FALCOSECURITY_LIBS_SOURCE_DIR="$SOURCE_DIR/libs"
     fi
 
